/**:
  ros__parameters:
    convolution_padding: 2
    distance_diff_threshold: 0.3
    parallel_beam_min_range_ratio: 0.02
    edge_threshold: 10.0
    surface_threshold: 0.1
    min_range: 0.1
    max_range: 1000.0
    n_blocks: 16
    max_iter: 40
    n_edge_neighbors: 10
    n_surface_neighbors: 20
    huber_k: 1.345
